### ISSUE TITLE
How to do automatic encoding/decoding for common javascript values?

### ISSUE THREAD

**Issue by serapath** [dominictarr/level-sublevel#107]
I was about to publish a module called `level-js-auto-en-ed-code` when i realized a problem.
The module currently is patching `.get`, `.put` to auto-encode and `.on` to auto-decode value likes:
```js
// type({}) == 'object'
// type(null) == 'null'
// type("hey") == 'string'
// type(true) == 'boolean'
// type(12) == 'number'
// type([]) == 'array'
```
...but I don't really know how to deal with `.createReadStream()` which will not auto-decode but stream all the values as strings (that's how i store them, because i'm using all the node modules mainly in the browser for frontend stuff)

I stumbled upon an issue where `level-sublevel/bytewise` is mentioned, which might already do that, but I couldn't find documentation on how to use it.

**Comment by serapath** [comment]
ok, I found a way to patch `.createReadStream` and `.createValueStream` too.
I'm still interested if there is another way how it should be done, but here is the module.
https://www.npmjs.com/package/level-js-auto-en-de-code

**Comment by dominictarr** [comment]
@serapath level takes an encoding option. use `level(path, {valueEncoding: 'json'})` and it will encode everything as json (you'll get objects as objects, but save them as strings).
but JSON isn't ideal for keys, because they will not be ordered consistently. I'd recommend using
`level-sublevel/bytewise` instead. just do `Sublevel = require('level-sublevel/bytewise); var db = Sublevel(level(path, {valueEncoding: 'json'}))`

**Comment by serapath** [comment]
Thx, i'll try

**Comment by NodeGuy** [comment]
Is there a way to specify value encoding for the sublevel only?

**Comment by dominictarr** [comment]
sorry, there isn't docs, but here https://github.com/dominictarr/level-sublevel/blob/master/test/mixed-value-encodings-per-sub.js I don't really use this module anymore, btw, I have moved on to https://github.com/flumedb/

**Comment by dominictarr** [comment]
sorry, there isn't docs, but here https://github.com/dominictarr/level-sublevel/blob/master/test/mixed-value-encodings-per-sub.js I don't really use this module anymore, btw, I have moved on to https://github.com/flumedb/

**Comment by NodeGuy** [comment]
Thank you for the pointers and Flume looks very cool!
