### ISSUE TITLE
Listen for changes on base `db` doesn't work for `db.sublevel('foorbar').put(...)`

### ISSUE THREAD

**Issue by serapath** [dominictarr/level-sublevel#108]
```js
db.on('put', function () { console.log('db') })
var sdb = db.sublevel('foobar')
sdb.on('put', function () { console.log('sdb') })
sdb.put('baz', 'quux')
```
only `"sdb"` gets logged to the console, but not `"db"`.

If I do `db.createReadStream().on('data', function(data) {console.log(data)})`, I can see the entry that was stored in the sublevel with the key prefixed with `!foobar!`, which is fine for me.

Is that a feature or a bug?
I'd like to monitor what sublevels do and maybe act on it.

**Comment by dominictarr** [comment]
This is a feature. the idea is to make every sublevel self contained.
ps, it's better to use `db.post(fn)` because it will respond to put, del, and batch.

**Comment by serapath** [comment]
thx a lot :-) ... did lots of `console.log`'s & `debugger;`  to understand better whats going on, so i closed the issue.

**Comment by serapath** [comment]
When I compose my frontend from many "view components", i try to pass down lots of sublevels.
Each component can then "track" certain keys in their sublevels (=duplex stream) to read/write updates to their sublevel. At the root db, I'd like to have a "switchboard" to wire up which component talks to which and how it might get synced to backends.

Not sure yet if it's stupid - but i'll publish it soon - think i found ways to patch sublevel so that it does what i need.
