### ISSUE TITLE
Cannot find levelup modules

### ISSUE THREAD

**Issue by cSchubes** [dominictarr/level-sublevel#119]
When using this library with TypeScript the included node_modules directory does not play nice. By using non-relative require statements like `var codec = require('levelup/lib/codec')` the compiler gets confused between the level-sublevel node modules directory and my project's node modules directory which contains a version of levelup that does not contain certain lib files.

I recommend a fix for this by either removing the node_modules folder from the repo (recommended) or at least making the require paths relative. If I have time I may submit a pull request with this fix.

**Comment by vweevers** [comment]
> I recommend a fix for this by either removing the node_modules folder from the repo

There is no `node_modules` committed to git. A require statement like `require('levelup/lib/codec')` is perfectly valid in Node.js. This sounds like a bug in TypeScript.
