### ISSUE TITLE
Get data from accross multiple sublevels

### ISSUE THREAD

**Issue by Delfshkrimm** [dominictarr/level-sublevel#122]
Hi!

I'm using sublevel in legacy mode and its features are great, but in my use case I sometimes need to manipulate data from accross multiple sublevels.
So I'dl like to be able to also use the toplevel db from which the the sublevels are created, to look for data inside different sublevels at the same time.
What is the proper way to implement this querying system that works both on sublevels and the main level databases?
Also, I'm using level-queryengine and jsonquery-engine to query on my sublevels db
```
var _sublevel = require('level-sublevel')
var _levelQuery = require('level-queryengine')
var _jsonqueryEngine = require('jsonquery-engine')
var _pairs = require('pairs')

var mainDb = require('level')('wut.db')
var subDb = _sublevel(mainDb)
var _db = subDb.sublevel('mysub')

var db = _levelQuery _db
db.query.use(_jsonqueryEngine())
db.ensureIndex('*', 'pairs', _pairs.index)
mainDb.put('foo', {bar: 'bar'}, function () {
  db.put('boom', {bang: 'bang'}, function () {
    db.get({bang: 'bang'}, function(err, entry) {
      mainDb.get({bang: 'bang'}, function (err, entry) {
        // should find document in sublevel 'mysub'
      })
    })
  })
})
```
Since the keys are prefixed with ÿ_SUB_NAME_ÿ_KEY_ when you stream the data from the main level database, a simple query like i've written won't work out of the box.

Thanks a lot for any help you could provide!
Mehdi

**Comment by dominictarr** [comment]
I'm sorry this module is no longer maintained
