### ISSUE TITLE
shared encodings

### ISSUE THREAD

**Issue by juliangruber** [dominictarr/level-sublevel#37]
When sublevels are treated more like stock databases, shouldn't they also have the default encodings that levelUp has?

**Comment by NodeGuy** [comment]
My expectation is that I should be able to treat a sublevel just like another LevelUp database and to pass it the same initialization options (including encodings).  There may be an abstraction design problem here.

**Comment by dominictarr** [comment]
@NodeGuy you can indeed do that, check the recent docs. (this issue was 4 years old)
