### ISSUE TITLE
createReadStream() on parent sublevels fail

### ISSUE THREAD

**Issue by ralphtheninja** [dominictarr/level-sublevel#55]
Assume I have a root sublevel named `db`, one sublevel below that is `sub1` which in turn also has a sublevel named `sub2`. Creating a read stream from the 'middle' sublevel doesn't work for me. Works fine if I use the lowest level. Also doesn't work if I use `db.createReadStream()`

``` js
var level = require('level')
var sublevel = require('level-sublevel')

var db = sublevel(level('./db'))
var sub1 = db.sublevel('sub1')
var sub2 = sub1.sublevel('sub2')

sub2.put('key', 'value', function (err) {
  sub1.createReadStream().on('data', function (data) {
    // no data, works well if using sub2 though.
    console.log('got data', data)
  })
})
```

Am I doing something wrong or is this also by design? I'm thinking that you should be able to create read streams from any sublevel and print out keys and values for that level.

**Comment by aral** [comment]
I just ran into this while trying to migrate my key structure en masse while using sublevel.

My ‘solution’ at the moment is to have a database singleton that allows access to the database via a variety of ways (see https://source.ind.ie/project/heartbeat-node/blob/tranquil-timelines/database.coffee)

e.g., 

	database = require './database'
	
	database.plain						# Reference to plain LevelUp database
	database.withSublevels				# level-sublevel-wrapped reference
	database.withPromises				# LevelUp promisified with Thrush
	database.withSublevelsAndPromises	# Wrapped in level-sublevel & promisified with Thrush

I use the ‘plain’ LevelUp reference when I want to iterate over all the keys/values and use the reference `.withSublevelsAndPromises` when I want to (as part of the same migration process) put the latest database schema version into the meta sublevel.

Not ideal but would be interesting to see if it evolves into an implementation of level-sublevel with Bluebird/Thrush promises that also allows aggregate iteration of sublevel records from parent levels. (No time to really concentrate on that at the moment — this works well enough and I have a couple of major refactorings I have to undertake on the app.)

Hope this helps illustrate at least my own use case — as niche (or not) as it may be :)
