### ISSUE TITLE
sublevel.close does not close original sublevel

### ISSUE THREAD

**Issue by maxogden** [dominictarr/level-sublevel#78]
test case:

this does not log any errors:

```js
var level = require('level-prebuilt')
var sub = require('level-sublevel')

var db = level('testdb', function() {
  db.close(function(err) {
    if (err) console.error(err)
    var reopened = level('testdb', function(err) {
      if (err) console.error(err)
      console.log('reopened')
    })
  })
})
```

but this does (on the second open)

```js
var level = require('level-prebuilt')
var sub = require('level-sublevel')

var db = level('testdb', function() {
  db = sub(db)
  db.close(function(err) {
    if (err) console.error(err)
    var reopened = level('testdb', function(err) {
      if (err) console.error(err)
      console.log('reopened')
    })
  })
})
```

so it seems that `sublevel.close` does not actually close the parent db

**Comment by dominicbarnes** [comment]
Has anything changed here? Currently, I cannot use `db.close()` at all because of this.

**Comment by dominictarr** [comment]
no this hasn't changed. Though, unless you are managing many level instances (dynamically creating them) you probably don't need to actually worry about closing them. @mcollina has suggested that closing a sublevel should clear all listeners, and I agree. the top sublevel could close the db.

I'd merge a PR that implements those, but this issue isn't a problem for me right now

**Comment by juliangruber** [comment]
potential fix: https://github.com/dominictarr/level-sublevel/pull/96
