### ISSUE TITLE
npm install fails with io.js

### ISSUE THREAD

**Issue by ralphtheninja** [dominictarr/level-sublevel#83]
- [ ] Update `levelup` dependency (once a new version supporting io.js is on npm)
- [ ] Update `level` devDependency (once a new version supporting io.js is on npm)

**Comment by ralphtheninja** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by dominictarr** [comment]
okay I updated those, but then I had a test fail...

**Comment by dominictarr** [comment]
okay this should be fixed now, but I encountered other errors...

```
[dominic@localhost level-sublevel]$ ~/Downloads/iojs-v1.0.3-linux-x64/bin/iojs test/level.js 
/home/dominic/c/level-sublevel/node_modules/leveldown/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at bindings (/home/dominic/c/level-sublevel/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/dominic/c/level-sublevel/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
```
I have never seen this one before...?

**Comment by ralphtheninja** [comment]
@dominictarr What do you mean updated those? Updated to what? :) Afaik neither of them have any versions on npm that works with io.js

**Comment by ralphtheninja** [comment]
Note: Updated issue description

**Comment by dominictarr** [comment]
ah, now I see

**Comment by hmalphettes** [comment]
`npm i level-sublevel` works nicely now with iojs-0.12

The newer versions of leveldown amd levelup that are required to support iojs only needed a patch version increment; we are already getting the latest levelup@0.19.0 and leveldown@1.0.1

Should we close this or do we want to explicitly celebrate by updating the versions in package.json as suggested by this bug?

Also note that test suite is green... beside one explained assertion failure: https://github.com/dominictarr/level-sublevel/issues/88

**Comment by reqshark** [comment]
this is wonderful news! :+1:
