### ISSUE TITLE
test assertion fail with iojs/node-0.12: JSON.stringify(Buffer) changed

### ISSUE THREAD

**Issue by hmalphettes** [dominictarr/level-sublevel#88]
I ran the tests in the master branch with iojs-1.2.0.
It all compiles nicely but one test assertion in the suite 'override json encoding' is failing.

This was a tentative fix: https://github.com/hmalphettes/level-sublevel/commit/a1242ae4f83a9f1b99809b90ca32629fdf6bfe6c

But it breaks with node-0.10

It turns out that
```
> var buf = new Buffer([1,2,3,4])
> JSON.stringify(buf)
```

Gives with iojs-1.2.0 and node-0.12:
```
'{"type":"Buffer","data":[1,2,3,4]}'
```

But with node-0.10:
```
'[1,2,3,4]'
```

The JSON encoder is defined here: https://github.com/rvagg/node-levelup/blob/master/lib/encodings.js#L37

Should we make the test tolerate both outputs?

**Comment by dominictarr** [comment]
yes, tolerate both outputs. This is now fixed in 6.5.4

**Comment by hmalphettes** [comment]
Thanks @dominictarr.
I was about to suggest this variant that reflects the internals of the JSON encoding done by level-up:
```
t.deepEqual(value, JSON.parse(JSON.stringify(buf)))
```

**Comment by dominictarr** [comment]
@hmalphettes unfortunately that won't work, I don't think that JSON parsing with buffers are actually reversable. certainly not in node@0.10

**Comment by hmalphettes** [comment]
@dominictarr indeed it is not reversible: it is a one way transformation to a POJO.
And that is how level-up JSON encoding works: when we read the value we don't get a Buffer back.

This way of writing the assertion is replicating what level-up does when it sets and then gets the value back.

That is what level-up json encoding does:
encode(Buffer([1,2,3,4])) -> JSON.stringify(Buffer([1,2,3,4])) -> "the string of a pojo that depends on the node version"

then when we read it:
value = decode(json-encoded-value) -> JSON.parse("the string of a pojo that depends on the node version")


It seems that this way of writing the assertion is more confusing so that is dead-end.


Here is stringify in action for Buffer(Array) in node-0.10 and iojs:
```
➜  tmp  nvm use 0.10.36
Now using node v0.10.36
➜  tmp  node
> process.version
'v0.10.36'
> JSON.parse(JSON.stringify(new Buffer([1,2,3,4])))
[ 1, 2, 3, 4 ]
> process.exit()
➜  tmp  nvm use iojs-v1.2.0
Now using io.js v1.2.0
➜  tmp  node
> process.version
'v1.2.0'
> JSON.parse(JSON.stringify(new Buffer([1,2,3,4])))
{ type: 'Buffer', data: [ 1, 2, 3, 4 ] }
```

**Comment by dominictarr** [comment]
right. Sure you are right but the test is okay now.
