### ISSUE TITLE
utf8 Chinese string as key cause strange behavior when using createReadStream

### ISSUE THREAD

**Issue by mike820324** [dominictarr/level-sublevel#89]
Hello, just reporting a strange behavior of createReadStream.
I'm using 
- iojs v1.3 and node v0.10.36
- levelup@0.19.0
- leveldown@0.10.4
- level-sublevel@6.4.5

When using a Chinese string as a key and calling createReadStream, some of the key will not be logged.
The following is the test code:
```javascript
var levelup = require('levelup');
var Sublevel = require('level-sublevel');

var db = Sublevel(levelup('./testDDB')).sublevel('test');

var ops =
[
	{
		type: 'put',
		key: '今天',
		value: 'today'
	},
	{
		type: 'put',
		key: '明天',
		value: 'tomorrow'
	},
	{
		type: 'put',
		key: '後天',
		value: 'the day after tomorrow'
	},
	// if a non-Chinese character prepend in front of the string,
	// the stream will work
	{
		type: 'put',
		key: 'a今天',
		value: 'today with an a in front'
	},
	{
		type: 'put',
		key: 'a明天',
		value: 'tomorrow with an a in front'
	},
	{
		type: 'put',
		key: 'a後天',
		value: 'the day after tomorrow with an a in front'
	}
];

db.batch(ops, function(err){
	if(err) console.log(err);
	else {
		// can't find key in stream
		// should log 6 values, but only three will be logged.
		db.createReadStream()
		.on('data', function(value){
			console.log(value.key);
		})
		.on('error', function(err) {
			console.log(err);
		});
	}
});
```
The expected output would be 
>a今天
a後天
a明天
今天
後天
明天

But the actual output is
>a今天
a後天
a明天

The strange part is that, if a non-Chinese character prepend in front of the Chinese string key, it will log the stream, otherwise it won't.

Also, I also test the following code, which use only levelup, and the result is correct.
```javascript
var levelup = require('levelup');
//var Sublevel = require('level-sublevel');

var db = levelup('./test1DDB');

var ops =
[
	{
		type: 'put',
		key: '今天',
		value: 'today'
	},
	{
		type: 'put',
		key: '明天',
		value: 'tomorrow'
	},
	{
		type: 'put',
		key: '後天',
		value: 'the day after tomorrow'
	},
	// if a non-Chinese character prepend in front of the string,
	// the stream will work
	{
		type: 'put',
		key: 'a今天',
		value: 'today with an a in front'
	},
	{
		type: 'put',
		key: 'a明天',
		value: 'tomorrow with an a in front'
	},
	{
		type: 'put',
		key: 'a後天',
		value: 'the day after tomorrow with an a in front'
	}
]

db.batch(ops, function(err){
	if(err) console.log(err);
	else {
		db.createReadStream()
		.on('data', function(value){
			console.log(value.key);
		});
	}
});
```
Any advice is helpful, thank you.

**Comment by mike820324** [comment]
After looking at the code for a while, I found out that it is the following line that cause the problem.
https://github.com/dominictarr/level-sublevel/blob/master/codec/index.js#L19
```javascript
exports.lowerBound = '\x00'
exports.upperBound = '\xff'
```
if changing the exports.upperBound = '\uffff', the result will be what it should be. But I'm not quite sure is it the right way to fix this problem. ;(

**Comment by ralphtheninja** [comment]
If I log the `opts` coming back from `ltgt.toLtgt()`

```
iterator opts { createIfMissing: true,
  errorIfExists: false,
  keyEncoding: 'utf8',
  valueEncoding: 'utf8',
  compression: true,
  db: { [Function] destroy: [Function], repair: [Function] },
  prefix: [ 'test' ],
  gte: '!test!\u0000',
  lte: '!test!ÿ' }
```

`lte` looks ok.

If I do a `createReadStream()` on the complete db with binary encoding the keys are:

```
<SlowBuffer 21 74 65 73 74 21 61 e4 bb 8a e5 a4 a9>
<SlowBuffer 21 74 65 73 74 21 61 e5 be 8c e5 a4 a9>
<SlowBuffer 21 74 65 73 74 21 61 e6 98 8e e5 a4 a9>
<SlowBuffer 21 74 65 73 74 21 e4 bb 8a e5 a4 a9>
<SlowBuffer 21 74 65 73 74 21 e5 be 8c e5 a4 a9>
<SlowBuffer 21 74 65 73 74 21 e6 98 8e e5 a4 a9>
```

I don't understand how `e4`, `e5` etc can be lexicographically sorted after `ff`

**Comment by dominictarr** [comment]
@mike820324 I think you do have the correct solution there. The `codec.upperBound` is used only when constructing ranges, so this is not a breaking change.

@ralphtheninja here is the problem.

``` js
> new Buffer('\xff')
<Buffer c3 bf>
> new Buffer('\uffff')
<Buffer ef bf bf>
```

\xff is not actually encoded as 255. I realized this a while ago, which is why v6 does not use \xff in the prefixes,
and now it is fixed here.

@mike820324 thank you for your issue, you where very thorougher... 

This is fixed in 6.4.6

**Comment by ralphtheninja** [comment]
:+1:

**Comment by mike820324** [comment]
@dominictarr wow thanks for the quick fix and my pleasure to help. :+1: 
It seems like the issue can be closed. :)

**Comment by ralphtheninja** [comment]
@dominictarr I'd like to know more of what's going on there. Have any pointers? Would like to read more on strings like '\xff' etc

**Comment by dominictarr** [comment]
@ralphtheninja sorry I can't really give you a better recommentation than to read the utf8 wikipedia page );
