### ISSUE TITLE
Unable to install as a dependency of pouchdb behind proxy

### ISSUE THREAD

**Issue by rick-li** [dominictarr/level-sublevel#90]
Hi, I want to install pouchdb in my company which is behind a http proxy.
I ran into an error saying unable to clone git://github.com/dominictarr/level-sublevel.git

I guess it's due to the repo url defined in package.json is git://... which doesn't work with http proxy.

is it possible to change to https:// url?

Thanks,
Rick

**Comment by ralphtheninja** [comment]
@rick-li You could submit a PR :)

**Comment by dominictarr** [comment]
@rick-li I think you need to post this issue on pouchdb. level-sublevel doesn't use any git urls, at least not with the latest version.

**Comment by rick-li** [comment]
I did several tests and turns out http:// or git:// doesn't matter.
Sorry for that, will open ticket to pouchdb.
