### ISSUE TITLE
Does not work with levelup v.1.2.1

### ISSUE THREAD

**Issue by aral** [dominictarr/level-sublevel#95]
Looks like LevelUp has breaking changes to its folder structure. 

Getting:

    Cannot find module 'levelup/lib/errors'

LevelUp 1.2.1 errors appear to be in node_modules/level-errors

**Comment by ralphtheninja** [comment]
@aral Can you produce a tiny script / some cli commands to reproduce this?

**Comment by aral** [comment]
Hey Lars-Magnus, odd — just created an empty project with LevelUp 1.2.1, LevelDown 1.4.1, and level-sublevel 6.4.6 and cannot reproduce.

Closing unless I run by it again.

**Comment by ralphtheninja** [comment]
@aral Note that you can do `npm i level`, which is a convenience module for wrapping `levelup` with `leveldown` as backend.

**Comment by dominictarr** [comment]
hmm, it seems that this would certainly break with the latest levelup, as level-sublevel depends on levelup/lib/* in 3 places. should be a pretty easy fix i hope though?

**Comment by ralphtheninja** [comment]
@dominictarr It should be fairly straight forward I think

**Comment by dominictarr** [comment]
sorry, actually since level-sublevel depends on the old levelup directly (instead of taking the deps off the levelup you pass in this will continue to work)
However, it looks like the things it depended on are now refactored out, so it would be easy to update.
